### ISSUE TITLE
$OKButton.DialogResult -eq 'OK' is always true.

### ISSUE THREAD

**Issue by robertwitteman** [mrobinson-ws/usertermination-azuread#1]
`114: if ($OKButton.DialogResult -eq 'OK')` always results as true and enters loop. Using the 'X' button on the dialog results in entering this if block.

**Comment by mrobinson-ws** [comment]
I think that's because the variables don't stick.  Or the throw isn't working.  Exit wouldn't work either I don't think though.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>


Mike Robinson

Technical Support Engineer

888-484-1012<tel:888-484-1012>

Need technical support? Create a ticket: ***@***.******@***.***>


[cid:Worksmart_EmailLogo_BlueTint_b83f0a42-5757-48b3-8f2b-71adc2076ca0.png] <https://www.worksmart.com>         [cid:BlueTint_Twitter_3c1c14f8-b984-4094-b5a6-288e240090cf.png]  <https://twitter.com/WorkSmart_Inc>            [cid:BlueTint_Facebook_db780300-f919-49b8-8991-f455a59ed5f5.png]  <https://www.facebook.com/WorkSmartIT>        [cid:BlueTint_LinkedIn_f65d91e1-72e4-4d42-95b3-a7c7f8ff56f2.png]  <https://www.linkedin.com/company/worksmart/>         [cid:BlueTint_Instagram_5c8d385a-57b0-4520-aaef-db97f973a950.png]  <https://www.instagram.com/worksmart.it.made.simple/>


 [cid:MicrosoftTeams-image(1)_af07553a-1f46-41fe-a4d3-070e7f30b2ad.png] <https://www.worksmart.com/webinars/> <https://info.worksmart.com/refersmart> <https://blog.worksmart.com/worksmart-continues-managed-it-services-expansion-in-atlanta> <https://blog.worksmart.com/knowledgecenter/phish-proof-cybersecurity-awareness-training> <https://info.worksmart.com/filesinthecloud> <https://info.worksmart.com/cybersecurity-awareness-month-week-2> <https://info.worksmart.com/worksmart-live-thats-a-wrap> <https://info.worksmart.com/worksmart-live-phish-proof> <https://info.worksmart.com/worksmart-live-to-security-and-beyond> <https://info.worksmart.com/worksmart-live-teams-for-everyday-people-part-2> <https://info.worksmart.com/worksmart-live-teams-for-everyday-people-part-1> <https://info.worksmart.com/leading-culture> <https://info.worksmart.com/backup-to-basics> <https://info.worksmart.com/files-files-everywhere> <https://info.worksmart.com/communicating-in-the-cloud> <https://info.worksmart.com/to-be-or-not-to-be-acquisitions> <https://info.worksmart.com/virtual-reality-strategy> <https://info.worksmart.com/virtual-reality-strategy>




________________________________
From: majorwitteman ***@***.***>
Sent: Monday, May 31, 2021 3:29:53 PM
To: mrobinson-ws/usertermination-azuread ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mrobinson-ws/usertermination-azuread] $OKButton.DialogResult -eq 'OK' is always true. (#1)


114: if ($OKButton.DialogResult -eq 'OK') always results as true and enters loop. Using the 'X' button on the dialog results in entering this if block.

**Comment by mrobinson-ws** [comment]
This is resolved.
